"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./components/Menu";
import Preloader from "./components/Preloader";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    const [isLoading, setIsLoading] = useState(true)
    useEffect(() => {
      setTimeout(() => {
        setIsLoading(false);
      }, 5900);
    }, []);
  return  isLoading ?(
    <html lang="en">
      <body className={inter.className}>
      <Preloader/>
      </body>
    </html>
  
) : (
    <html lang="en">
      <body className={inter.className}>
        <Menu/>
        {children}
      </body>
    </html>
  );
}
